import type { NextPage } from 'next'
import Head from 'next/head'
import { Image } from '@chakra-ui/react'
import styles from '../styles/Home.module.css'
import { CreatorCard } from '../components/CreatorCard'

const creators = [
  {
    "name": "Justin Sullivan",
    "profile": "/justin-sullivan",
    "speciality": "Ultrices morbi arcu",
  },
  {
    "name": "Justine Mendoza",
    "profile": "/justine-mendoza",
    "speciality": "Ultrices morbi arcu",
  },
  {
    "name": "JustinSays",
    "profile": "/justin-says",
    "speciality": "Est interdum lobortis",
  },
  {
    "name": "Justined",
    "profile": "/justined",
    "speciality": "Amet velit",
  }
]


const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Image src="/livelink_logo_text.svg" alt="Livelink Logo" width={172} height={116} />

        {creators.map((creator) => (
          <CreatorCard creator={creator} />
        ))}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://livelink.vip"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/livelink_logo_text.svg" alt="Livelink Logo" width={90} height={35} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
