import type { NextPage } from 'next'
import Head from 'next/head'
import { Image } from '@chakra-ui/react'
import styles from '../styles/Home.module.css'
import { CreatorCard } from '../components/CreatorCard'
import { GetServerSideProps } from 'next'
import { CreatorsType, CreatorType } from '../types/creatorTypes'
import { Link } from '@chakra-ui/react'


const Home: NextPage<CreatorsType> = ({ creators }: CreatorsType) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>LiveLink</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/livelink_logo_text.svg" />
      </Head>

      <main className={styles.main}>
        <Link href="/">
          <Image src="/livelink_logo_text.svg" alt="Livelink Logo" width={172} height={116} />
        </Link>

        {creators.map((creator: CreatorType) => (
          <div key={creator.slug}>
            <CreatorCard creator={creator} />
          </div>
        ))}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://livelink.vip"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/livelink_logo_text.svg" alt="Livelink Logo" width={90} height={35} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home

export const getServerSideProps: GetServerSideProps = async () => {
  const req = await fetch('http://localhost:3000/api/creators')
  const creators = await req.json()
    return {
        props: {
          creators: creators
        },
    };
}